### ISSUE TITLE
Launcher release binary is almost 70MB

### ISSUE THREAD

**Issue by janisozaur** [IntelOrca/OpenLauncher#2] opened 2022-06-13 07:25 UTC
Current https://github.com/IntelOrca/OpenLauncher/releases/tag/v0.1 release weighs 67.9MB, according to GitHub, while the entire repository is under 0.5MB. It seems there might be some unnecessary data in the binary.

**Comment by IntelOrca** [comment] 2022-06-13 08:16
Unfortunately this is the nature of self contained .NET apps. I think even self contained C# console apps weigh over 30 MiB with compression and trimming. I believe this is improving with later versions of .NET, but it still is not great. For this, it has to bundle the entire .NET 6 and WPF runtime.

Without self-contained, the user would need a .NET 6+ runtime installed on their machine. Then the launcher would only be a few MiB.

Moving to a different framework like AvaloniaUI (for cross platform) might help and could be more lightweight than WPF. Alternatively, GTK bindings - but these would just add native dependency requirements. You'll never beat a C app that just uses WinAPI for space usage, but they can't be written in 5 minutes like this can.

**Comment by janisozaur** [comment] 2022-06-13 08:51
> Without self-contained, the user would need a .NET 6+ runtime installed on their machine.

Isn't it already the standard? What happens if the user doesn't have it and tries to launch it anyway? Is there an adequate error message?

**Comment by IntelOrca** [comment] 2022-06-13 09:11
> Isn't it already the standard?

https://github.com/dotnet/core/issues/6411

They do not plan to ship .NET with Windows anymore. The problem is that it relies on the user having a supported version, and .NET releases move so quickly now - it would prevent developers from using the latest and greatest. This was the issue with .NET framework I believe. Self contained apps while have the disadvantage of being large, but are guaranteed to work out the box across most systems, with no preinstallation of dependencies.

Look at the trend, you'll see a lot of modern apps, any electron app for that matter, just bundle everything it needs to run and be large because of it. But therefore have little to no risk of not having a dependency, or attempting to share versions of libraries across apps which need to stay compatible. You might not like it, but that is the way things are going.

**Comment by IntelOrca** [comment] 2022-06-14 18:33
Now that the launcher uses AvaloniaUI, the final size with .NET bundled is about 40 MiB. Without .NET bundled, it is about 25 MIB.

**Closed** 2022-06-19 00:01 UTC
